namespace: default
resources:
  - nginx.yaml
  - mysql.yaml
  - frontend.yaml
  - backend.yaml
  configMapGenerator:
  - name: nginx
    files:
      - configs/default.conf
secretGenerator:
  - name: secret
    files:
      - configs/secret.json